version: '3'

services:
  fluentd:
    container_name: my_fluentd
    build: .
    ports:
      - 9880:9880
      - 24224:24224
      - 24220:24220
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
      - ./fizzbuzz.py:/fluentd/etc/fizzbuzz.py
    # depends_on:
    #   - elasticsearch

  # web:
  #   image: httpd
  #   ports:
  #     - 80:80
  #   logging:
  #     driver: fluentd
  #     options:
  #       fluentd-address: 0.0.0.0:24224
  #       tag: httpd.access
  #   depends_on:
  #     - fluentd

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - 9200:9200

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.13.1
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elasticsearch

  # prometheus:
  #   container_name: my_prometheus
  #   build: prometheus
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - ./prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yml

  # forwarder:
  #   container_name: my_forwarder
  #   build: log-forwarder-aggregator
  #   ports:
  #     - 24224:24224
  #     - 8888:8888
  #   volumes:
  #     - ./log-forwarder-aggregator/forwarder/fluent.conf:/fluentd/etc/fluent.conf

  # primary_aggregator:
  #   container_name: my_primary_aggregator
  #   build: log-forwarder-aggregator
  #   volumes:
  #     - ./log-forwarder-aggregator/aggregator/fluent.conf:/fluentd/etc/fluent.conf

  # secondary_aggregator:
  #   container_name: my_secondary_aggregator
  #   build: log-forwarder-aggregator
  #   volumes:
  #     - ./log-forwarder-aggregator/aggregator/fluent.conf:/fluentd/etc/fluent.conf

networks:
  default:
    driver: bridge