version: "3"
services:
  hadoop:
    container_name: hadoop
    ports:
      - "9870:9870"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/hadoop/etc/hadoop
      - ./start:/hadoop/start
    networks:
      - hadoop

networks:
  hadoop:
