version: '3'

services:
  elasticsearch:
    build: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  logstash:
    build: logstash
    ports:
      - 9600:9600
    volumes:
      - ./logstash/conf:/usr/share/logstash/pipeline/
    tty: true
    depends_on:
      - elasticsearch

networks:
  elastic:
    driver: bridge
