version: '3'

services:
  elasticsearch:
    container_name: my_elasticsearch
    build: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: my_kibana
    image: docker.elastic.co/kibana/kibana:7.5.2
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  curator:
    container_name: my_curator
    build: curator
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      CRON: 0 0 * * *
      CONFIG_FILE: /usr/share/curator/config/curator.yml
      COMMAND: /usr/share/curator/config/action.yml
      UNIT_COUNT: 2
    volumes:
      - ./curator/config:/usr/share/curator/config
    depends_on:
      - elasticsearch

networks:
  elastic:
    driver: bridge
