apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
  template:
    metadata:
      labels:
        app: flink
        component: master
    spec:
      containers:
        - name: master
          image: flink:1.13.0-scala_2.12
          args:
            - jobmanager
          ports:
            - containerPort: 6123
              name: rpc
            - containerPort: 6124
              name: blob
            - containerPort: 6125
              name: query
            - containerPort: 8081
              name: ui
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: flink-master
