#!/bin/bash

/usr/sbin/sshd
start-dfs.sh

hdfs dfs -mkdir -p /tmp
hdfs dfs -mkdir -p /user/hive/warehouse
hdfs dfs -chmod g+w /tmp
hdfs dfs -chmod g+w /user/hive/warehouse

hiveserver2 &

schematool -dbType derby -initSchema

# daemonize
while true; do
  sleep 1000
done