version: "3"
services:
  hadoop:
    container_name: hadoop
    ports:
      - "9870:9870"
      - "9864:9864"
    build:
      context: .
    volumes:
      - ./config:/hadoop/etc/hadoop
      - ./start:/hadoop/start
    networks:
      - hadoop

networks:
  hadoop:
