version: "3"
services:
  hadoop:
    container_name: hadoop
    ports:
      - "9870:9870"
      - "9864:9864"
      - "19888:19888"
    build:
      context: .
    volumes:
       - ./start:/hadoop/start
    networks:
      - hadoop

networks:
  hadoop:
