version: "3"
services:
  hadoop1:
    container_name: hadoop1
    ports:
      - "9870:9870"
      - "8088:8088"
      - "19888:19888"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/hadoop/etc/hadoop
      - ./master/start_active:/hadoop/start
    depends_on:
      - zk1
      - zk2
      - zk3
    networks:
      - hadoop

  hadoop2:
    container_name: hadoop2
    ports:
      - "9871:9870"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/hadoop/etc/hadoop
      - ./master/start_standby:/hadoop/start
    depends_on:
      - zk1
      - zk2
      - zk3
    networks:
      - hadoop

  hadoop3:
    container_name: hadoop3
    ports:
      - "9872:9870"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/hadoop/etc/hadoop
      - ./master/start_standby:/hadoop/start
    depends_on:
      - zk1
      - zk2
      - zk3
    networks:
      - hadoop

  hadoop4:
    container_name: hadoop4
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/hadoop/etc/hadoop
      - ./slave/start:/hadoop/start
    networks:
      - hadoop

  hadoop5:
    container_name: hadoop5
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/hadoop/etc/hadoop
      - ./slave/start:/hadoop/start
    networks:
      - hadoop

  zk1:
    image: zookeeper:3.8
    container_name: zk1
    restart: always
    hostname: zk1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
    networks:
      - hadoop

  zk2:
    image: zookeeper:3.8
    container_name: zk2
    restart: always
    hostname: zk2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
    networks:
      - hadoop

  zk3:
    image: zookeeper:3.8
    container_name: zk3
    restart: always
    hostname: zk3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
    networks:
      - hadoop

  fluentd:
    container_name: fluentd
    ports:
      - 9880:9880
      - 24224:24224
      - 24220:24220
    build:
      context: ./fluentd
      dockerfile: Dockerfile
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
    networks:
      - hadoop

networks:
  hadoop:
