version: "3"
services:
  hadoop1:
    container_name: hadoop1
    ports:
      - "9870:9870"
      - "8088:8088"
      - "19888:19888"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/hadoop/etc/hadoop
      - ./master/start:/hadoop/start
    networks:
      - hadoop

  hadoop2:
    container_name: hadoop2
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/hadoop/etc/hadoop
      - ./slave/start:/hadoop/start
    networks:
      - hadoop

  hadoop3:
    container_name: hadoop3
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/hadoop/etc/hadoop
      - ./slave/start:/hadoop/start
    networks:
      - hadoop

  fluentd:
    container_name: fluentd
    ports:
      - 9880:9880
      - 24224:24224
      - 24220:24220
    build:
      context: ./fluentd
      dockerfile: Dockerfile
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
    networks:
      - hadoop

networks:
  hadoop:
