#!/bin/bash

/usr/sbin/sshd

hdfs --daemon start journalnode

hdfs namenode -format
hdfs zkfc -formatZK
start-dfs.sh

start-yarn.sh
mapred --daemon start historyserver

# daemonize
while true; do
  sleep 1000
done