version: "3"
services:
  hadoop-eco:
    container_name: hadoop-eco
    ports:
      - "9870:9870"
    build:
      context: .
    volumes:
      - ./config/hadoop:/hadoop/etc/hadoop
      - ./config/hive:/hive/conf
      - ./config/hbase/hbase-env.sh:/hbase/conf/hbase-env.sh
      - ./config/hbase/hbase-site.xml:/hbase/conf/hbase-site.xml
      - ./script/hadoop:/hadoop/script
      - ./script/pig:/pig/script
      - ./script/hive:/hive/script
    networks:
      - hadoop

networks:
  hadoop:
