version: "3"

services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper1
    container_name: kafka-zookeeper1
    ports:
      - 22181:22181
    environment:
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper1:22888:23888;zookeeper2:32888:33888;zookeeper3:42888:43888

  zookeeper2:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper2
    container_name: kafka-zookeeper2
    ports:
      - 32181:32181
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVERS: zookeeper1:22888:23888;zookeeper2:32888:33888;zookeeper3:42888:43888

  zookeeper3:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper3
    container_name: kafka-zookeeper3
    ports:
      - 42181:42181
    environment:
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SERVERS: zookeeper1:22888:23888;zookeeper2:32888:33888;zookeeper3:42888:43888

  broker1:
    build:
      context: ./broker
      dockerfile: Dockerfile
    hostname: broker1
    container_name: kafka-broker1
    depends_on:
      - kafka-zookeeper1
      - kafka-zookeeper2
      - kafka-zookeeper3
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:22181,zookeeper2:32181,zookeeper3:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:29092
      CONFLUENT_SUPPORT_METRICS_ENABLE: false
      KAFKA_OPTS: -javaagent:/usr/share/java/kafka/jolokia-jvm-1.7.1.jar

  broker2:
    build:
      context: ./broker
      dockerfile: Dockerfile
    hostname: broker2
    container_name: kafka-broker2
    depends_on:
      - kafka-zookeeper1
      - kafka-zookeeper2
      - kafka-zookeeper3
    ports:
      - 39092:39092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:22181,zookeeper2:32181,zookeeper3:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:39092
      CONFLUENT_SUPPORT_METRICS_ENABLE: false
      KAFKA_OPTS: -javaagent:/usr/share/java/kafka/jolokia-jvm-1.7.1.jar

  broker3:
    build:
      context: ./broker
      dockerfile: Dockerfile
    hostname: broker3
    container_name: kafka-broker3
    depends_on:
      - kafka-zookeeper1
      - kafka-zookeeper2
      - kafka-zookeeper3
    ports:
      - 49092:49092
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:22181,zookeeper2:32181,zookeeper3:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker3:49092
      CONFLUENT_SUPPORT_METRICS_ENABLE: false
      KAFKA_OPTS: -javaagent:/usr/share/java/kafka/jolokia-jvm-1.7.1.jar

  client:
    image: confluentinc/cp-kafka:7.0.1
    hostname: cli
    container_name: kafka-client
    depends_on:
      - kafka-broker1
      - kafka-broker2
      - kafka-broker3
    entrypoint: /bin/sh
    tty: true

  connect:
    image: confluentinc/cp-kafka-connect
    hostname: connect
    container_name: kafka-connect
    volumes:
      - ./zaiko/latest.txt:/home/appuser/zaiko-latest.txt
    depends_on:
      - kafka-broker1
      - kafka-broker2
      - kafka-broker3
    environment:
      CONNECT_BOOTSTRAP_SERVERS: broker1:29092
      CONNECT_REST_PORT: 28082
      CONNECT_GROUP_ID: quickstart
      CONNECT_CONFIG_STORAGE_TOPIC: quickstart-config
      CONNECT_OFFSET_STORAGE_TOPIC: quickstart-offsets
      CONNECT_STATUS_STORAGE_TOPIC: quickstart-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/filestream-connectors

networks:
  kafka: