version: "3"

services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper1
    container_name: kafka-zookeeper1
    ports:
      - 22181:22181
    environment:
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper1:22888:23888;zookeeper2:32888:33888;zookeeper3:42888:43888

  zookeeper2:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper2
    container_name: kafka-zookeeper2
    ports:
      - 32181:32181
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVERS: zookeeper1:22888:23888;zookeeper2:32888:33888;zookeeper3:42888:43888

  zookeeper3:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper3
    container_name: kafka-zookeeper3
    ports:
      - 42181:42181
    environment:
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SERVERS: zookeeper1:22888:23888;zookeeper2:32888:33888;zookeeper3:42888:43888

  broker1:
    build:
      context: ./broker
    hostname: broker1
    container_name: kafka-broker1
    depends_on:
      - kafka-zookeeper1
      - kafka-zookeeper2
      - kafka-zookeeper3
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:22181,zookeeper2:32181,zookeeper3:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:29092
      CONFLUENT_SUPPORT_METRICS_ENABLE: false
      KAFKA_OPTS: -javaagent:/usr/share/java/kafka/jolokia-jvm-1.7.1.jar=port=8778,host=broker1

  broker2:
    build:
      context: ./broker
    hostname: broker2
    container_name: kafka-broker2
    depends_on:
      - kafka-zookeeper1
      - kafka-zookeeper2
      - kafka-zookeeper3
    ports:
      - 39092:39092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:22181,zookeeper2:32181,zookeeper3:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:39092
      CONFLUENT_SUPPORT_METRICS_ENABLE: false
      KAFKA_OPTS: -javaagent:/usr/share/java/kafka/jolokia-jvm-1.7.1.jar=port=8778,host=broker2

  broker3:
    build:
      context: ./broker
    hostname: broker3
    container_name: kafka-broker3
    depends_on:
      - kafka-zookeeper1
      - kafka-zookeeper2
      - kafka-zookeeper3
    ports:
      - 49092:49092
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:22181,zookeeper2:32181,zookeeper3:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker3:49092
      CONFLUENT_SUPPORT_METRICS_ENABLE: false
      KAFKA_OPTS: -javaagent:/usr/share/java/kafka/jolokia-jvm-1.7.1.jar=port=8778,host=broker3

  client:
    image: confluentinc/cp-kafka:7.0.1
    hostname: client
    container_name: kafka-client
    # volumes:
    #   - ./kafka-sandbox-assembly-1.0.jar:/home/appuser/kafka-sandbox-assembly-1.0.jar
    depends_on:
      - kafka-broker1
      - kafka-broker2
      - kafka-broker3
    entrypoint: /bin/sh
    tty: true

  proxy:
    image: confluentinc/cp-kafka-rest:7.0.1
    hostname: proxy
    container_name: kafka-proxy
    depends_on:
      - kafka-broker1
      - kafka-broker2
      - kafka-broker3
    ports:
      - 8082:8082
    environment:
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_BOOTSTRAP_SERVERS: broker1:29092,broker2:39092,broker3:49092

  connect:
    build:
      context: ./connect
    hostname: connect
    container_name: kafka-connect
    volumes:
      - ./zaiko/latest.txt:/home/appuser/zaiko-latest.txt
    depends_on:
      - kafka-broker1
      - kafka-broker2
      - kafka-broker3
      - mysql
    environment:
      CONNECT_BOOTSTRAP_SERVERS: broker1:29092,broker2:39092,broker3:49092
      CONNECT_REST_PORT: 28082
      CONNECT_GROUP_ID: quickstart
      CONNECT_CONFIG_STORAGE_TOPIC: quickstart-config
      CONNECT_OFFSET_STORAGE_TOPIC: quickstart-offsets
      CONNECT_STATUS_STORAGE_TOPIC: quickstart-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/filestream-connectors,/usr/share/confluent-hub-components,/etc/kafka-connect/jars

  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: kafka-mysql
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    privileged: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    

  # fluentd:
  #   build:
  #     context: ./fluentd
  #   hostname: fluentd
  #   container_name: kafka-fluentd
  #   ports:
  #     - 9880:9880
  #     - 24224:24224
  #   volumes:
  #     - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
  #   depends_on:
  #     - kafka-broker1
  #     - kafka-broker2
  #     - kafka-broker3

networks:
  kafka: