#!/bin/bash

/usr/sbin/sshd

hdfs --daemon start journalnode

# 初期active用namenodeの起動を待つ
# stanby用namenodeのコマンドを、activeのフォーマット完了後におこなう必要があるため
while true; do
  status=`curl -LI hadoop1:9870/isActive -o /dev/null -w '%{http_code}\n' -s`
  if [ "$status" = "200" ]; then
    break
  fi
  sleep 10s
done

hdfs namenode -bootstrapStandby
start-dfs.sh

# daemonize
while true; do
  sleep 1000
done
