version: "3"
services:
  jobmanager:
    image: flink:1.13.0-scala_2.12
    networks:
      - flink
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    image: flink:1.13.0-scala_2.12
    depends_on:
      - jobmanager
    networks:
      - flink
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2

networks:
  flink:
